language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.5
  - 2.5.3
  - 2.6
  - ruby-head

matrix:
  allow_failures:
    - rvm: 2.6
    - rvm: ruby-head

branches:
  only:
    - master
    - omnibus/3.2-stable

bundler_args: --jobs 7

before_install: gem install bundler

script: bundle exec rake travis:ci
